# Generated by Django 5.2.14 on 2026-05-07 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('inn', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('entity', models.CharField(blank=True, max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.enterprise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('unit', models.CharField(choices=[('m3', 'м3'), ('m2', 'м2'), ('pcs', 'шт'), ('kg', 'кг'), ('bag', 'мешок'), ('roll', 'рулон'), ('set', 'комплект')], max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_factor', models.DecimalField(decimal_places=3, default=0.05, max_digits=5)),
                ('delivery_days', models.PositiveSmallIntegerField(default=5)),
                ('stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('alternative_group', models.CharField(db_index=True, max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.enterprise')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.materialcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('object_type', models.CharField(choices=[('house', 'Жилой дом'), ('apartment', 'Квартира'), ('office', 'Офис'), ('retail', 'Торговое помещение'), ('auxiliary', 'Вспомогательное сооружение')], default='house', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('workers', models.PositiveSmallIntegerField(default=6)),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('calculated', 'Рассчитан'), ('in_progress', 'В работе'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.enterprise')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('foundation', 'Фундамент'), ('walls', 'Стены'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('interior', 'Отделка'), ('engineering', 'Инженерные работы')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(max_length=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_factor', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('labor_hours', models.DecimalField(decimal_places=2, max_digits=14)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('foundation', 'Фундамент'), ('walls', 'Стены'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('interior', 'Отделка'), ('engineering', 'Инженерные работы')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_days', models.PositiveSmallIntegerField(default=1)),
                ('tech_break_days', models.PositiveSmallIntegerField(default=0)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('workers', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='planned', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to='core.project')),
            ],
            options={
                'ordering': ['sequence', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=5)),
                ('reliability_percent', models.PositiveSmallIntegerField(default=95)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.enterprise')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('enterprise', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(max_length=12)),
                ('needed_by', models.DateField()),
                ('order_before', models.DateField()),
                ('lead_time_days', models.PositiveSmallIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ordered', 'Заказано'), ('delivered', 'Поставлено')], default='planned', max_length=20)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_items', to='core.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
            options={
                'ordering': ['order_before', 'needed_by'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='LaborNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('foundation', 'Фундамент'), ('walls', 'Стены'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('interior', 'Отделка'), ('engineering', 'Инженерные работы')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('unit', models.CharField(default='m2', max_length=12)),
                ('productivity_per_worker_day', models.DecimalField(decimal_places=3, max_digits=12)),
                ('base_labor_hours', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tech_break_days', models.PositiveSmallIntegerField(default=0)),
                ('recommended_crew_size', models.PositiveSmallIntegerField(default=4)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=850, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_norms', to='core.enterprise')),
            ],
            options={
                'ordering': ['work_type', 'name'],
                'unique_together': {('enterprise', 'work_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('foreman', 'Прораб'), ('estimator', 'Сметчик'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'enterprise')},
            },
        ),
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('foundation', 'Фундамент'), ('walls', 'Стены'), ('roof', 'Кровля'), ('facade', 'Фасад'), ('interior', 'Отделка'), ('engineering', 'Инженерные работы')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('coefficient', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('quantity_override', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('workers_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.project')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('project', 'work_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('enterprise', 'name', 'alternative_group')},
        ),
    ]
