# Generated by Django 5.2.14 on 2026-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='kind',
            field=models.CharField(choices=[('personal', 'Личное пространство'), ('company', 'Компания')], default='company', max_length=20),
        ),
    ]
