# Generated by Django 5.2.14 on 2026-05-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplierapplication_alter_enterprise_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('planned_role', models.CharField(choices=[('developer', 'Застройщик'), ('foreman', 'Прораб'), ('builder', 'Исполнитель'), ('estimator', 'Сметчик'), ('viewer', 'Наблюдатель')], default='viewer', max_length=24)),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ожидает участника'), ('assigned', 'Назначен'), ('cancelled', 'Отменено')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_seats', to='core.enterprise')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_seats', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_seats', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.project')),
            ],
            options={
                'ordering': ['status', 'id'],
            },
        ),
    ]
