# Generated by Django 5.2.14 on 2026-05-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgoal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='core.projectgoal'),
        ),
    ]
